version: "3.8"

services:
  mysql:
    build: ./mysql-service
    container_name: test-mysql-service
    ports:
      - "6603:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: libreria
    volumes:
      - ./mysql-service/data:/var/lib/mysql

  nodejs:
    build: ./nodejs-service
    container_name: test-nodejs-service
    ports:
      - "4000:4000"
    depends_on:
      - mysql
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: libreria
      MYSQL_HOST: mysql
